// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SMSDbContext))]
    partial class SMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AdmissionChallan", b =>
                {
                    b.Property<long>("acf_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("acf_id"));

                    b.Property<long>("acf_appid")
                        .HasColumnType("bigint");

                    b.Property<long?>("acf_cancelledby")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("acf_cancelledon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("acf_dateofissue")
                        .HasColumnType("datetime2");

                    b.Property<string>("acf_discountapprovalfilename")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("acf_expirydate")
                        .HasColumnType("datetime2");

                    b.Property<long>("acf_fineAfterDueDate")
                        .HasColumnType("bigint");

                    b.Property<string>("acf_paidfilename")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("acf_paidon")
                        .HasColumnType("datetime2");

                    b.Property<long>("acf_preparedby")
                        .HasColumnType("bigint");

                    b.Property<long>("acf_schid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("acf_tobepaidby")
                        .HasColumnType("datetime2");

                    b.Property<long>("acf_totalamount")
                        .HasColumnType("bigint");

                    b.HasKey("acf_id");

                    b.ToTable("admissionChallan");
                });

            modelBuilder.Entity("Domain.Entities.AdmissionChallanDetails", b =>
                {
                    b.Property<long>("acd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("acd_id"));

                    b.Property<long>("acd_acfid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("acd_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("acd_chargestype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("acd_detialid")
                        .HasColumnType("bigint");

                    b.Property<long>("acd_schid")
                        .HasColumnType("bigint");

                    b.HasKey("acd_id");

                    b.ToTable("admissionChallanDetails");
                });

            modelBuilder.Entity("Domain.Entities.Application.Applicant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("app_date");

                    b.Property<long?>("AppliedForClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_appliedforclass");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("app_approvedby");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("app_approvedon");

                    b.Property<string>("BFormNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_BFORM_number");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("app_createdby");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("app_dateofbirth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_fullname");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_gender");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_prevschool_grade");

                    b.Property<string>("MotherTongue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_mothertongue");

                    b.Property<float?>("Percentage")
                        .HasColumnType("real")
                        .HasColumnName("app_prevschool_percentage");

                    b.Property<string>("PrevSchool")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_prevschool_name");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_schid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_status");

                    b.Property<string>("YearsAttended")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_prevschool_yearsattended");

                    b.Property<int>("classCategory")
                        .HasColumnType("int")
                        .HasColumnName("app_prevschool_category");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_contactNo");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_Email");

                    b.HasKey("Id");

                    b.ToTable("applicants");
                });

            modelBuilder.Entity("Domain.Entities.Application.ApplicantGuardian", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("agu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_address");

                    b.Property<long>("ApplicantId")
                        .HasColumnType("bigint")
                        .HasColumnName("agu_appid");

                    b.Property<string>("Cnic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_cnicNo");

                    b.Property<string>("CnicFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_cnicfilename");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_contactnumber");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_fullname");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_gender");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_occupation");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_qualifications");

                    b.Property<string>("RelationWithApplicant")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agu_relationwithapplicant");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint")
                        .HasColumnName("agu_schid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("applicantguardians");
                });

            modelBuilder.Entity("Domain.Entities.Application.ApplicantSibling", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("asg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicantId")
                        .HasColumnType("bigint")
                        .HasColumnName("asg_appid");

                    b.Property<string>("Bform")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asg_Bform");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asg_Name");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint")
                        .HasColumnName("asg_schid");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("asg_stuid");

                    b.Property<int>("classNo")
                        .HasColumnType("int")
                        .HasColumnName("asg_class");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("applicantsibling");
                });

            modelBuilder.Entity("Domain.Entities.Application.QuickLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuickLinks");
                });

            modelBuilder.Entity("Domain.Entities.Banda", b =>
                {
                    b.Property<long>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ban_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BanId"));

                    b.Property<bool>("BanActive")
                        .HasColumnType("bit")
                        .HasColumnName("ban_active");

                    b.Property<DateTime>("BanCreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ban_created_at");

                    b.Property<bool>("BanCurrentlyLogin")
                        .HasColumnType("bit")
                        .HasColumnName("ban_currentlylogin");

                    b.Property<int>("BanFailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("ban_failedattempts");

                    b.Property<DateTime>("BanLastLoggedOffDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ban_lastloggedoffdatetime");

                    b.Property<string>("BanPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ban_password");

                    b.Property<string>("BanResetToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ban_ResetToken");

                    b.Property<DateTime?>("BanResetTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ban_ResetTokenExpiresAt");

                    b.Property<string>("BanRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ban_role");

                    b.Property<long?>("BanSchId")
                        .HasColumnType("bigint")
                        .HasColumnName("ban_schid");

                    b.Property<string>("Ban_username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ban_loginname");

                    b.HasKey("BanId");

                    b.HasIndex("Ban_username")
                        .IsUnique();

                    b.ToTable("Bandas");
                });

            modelBuilder.Entity("Domain.Entities.BankDetails", b =>
                {
                    b.Property<long>("bnk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("bnk_id"));

                    b.Property<string>("bnk_accountnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bnk_accounttitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bnk_active")
                        .HasColumnType("bit");

                    b.Property<string>("bnk_branchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bnk_ibannumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bnk_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("bnk_schid")
                        .HasColumnType("bigint");

                    b.HasKey("bnk_id");

                    b.ToTable("bankDetails");
                });

            modelBuilder.Entity("Domain.Entities.ClassSections", b =>
                {
                    b.Property<long>("cse_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("cse_id"));

                    b.Property<long>("cse_classId")
                        .HasColumnType("bigint");

                    b.Property<string>("cse_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cse_lastrollNo")
                        .HasColumnType("int");

                    b.Property<string>("cse_prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("cse_schId")
                        .HasColumnType("bigint");

                    b.Property<int>("cse_year")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("requiredAssistant")
                        .HasColumnType("bit");

                    b.HasKey("cse_id");

                    b.ToTable("classSections");
                });

            modelBuilder.Entity("Domain.Entities.ClassSubjects", b =>
                {
                    b.Property<long>("csb_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("csb_id"));

                    b.Property<long>("csb_classid")
                        .HasColumnType("bigint");

                    b.Property<long>("csb_schid")
                        .HasColumnType("bigint");

                    b.Property<long>("csb_subjectID")
                        .HasColumnType("bigint");

                    b.Property<int>("csb_year")
                        .HasColumnType("int");

                    b.HasKey("csb_id");

                    b.ToTable("ClassSubjects");
                });

            modelBuilder.Entity("Domain.Entities.ClassTimeTable", b =>
                {
                    b.Property<long>("ctt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ctt_id"));

                    b.Property<string>("ctt_Friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctt_Monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctt_Saturday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctt_Thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctt_Tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctt_Wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ctt_classid")
                        .HasColumnType("bigint");

                    b.Property<long>("ctt_schid")
                        .HasColumnType("bigint");

                    b.Property<long>("ctt_sectionid")
                        .HasColumnType("bigint");

                    b.Property<string>("ctt_timeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ctt_id");

                    b.ToTable("ClassTimeTable");
                });

            modelBuilder.Entity("Domain.Entities.Classes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cls_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("cls_active");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cls_category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cls_description");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("cls_prefix");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint")
                        .HasColumnName("cls_schid");

                    b.Property<bool>("SubjectWiseTeaching")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FeeAndCharges", b =>
                {
                    b.Property<long>("fac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("fac_id"));

                    b.Property<string>("fac_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fac_feeHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("fac_schid")
                        .HasColumnType("bigint");

                    b.HasKey("fac_id");

                    b.ToTable("feeAndCharges");
                });

            modelBuilder.Entity("Domain.Entities.FeeAndChargesAmount", b =>
                {
                    b.Property<long>("fcm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("fcm_id"));

                    b.Property<long>("fcm_FeeHead")
                        .HasColumnType("bigint");

                    b.Property<long>("fcm_amount")
                        .HasColumnType("bigint");

                    b.Property<long?>("fcm_clsID")
                        .HasColumnType("bigint");

                    b.HasKey("fcm_id");

                    b.ToTable("feeAndChargesAmounts");
                });

            modelBuilder.Entity("Domain.Entities.SchoolParams", b =>
                {
                    b.Property<long>("spa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("spa_id"));

                    b.Property<string>("spa_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spa_paramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spa_paramValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("spa_schid")
                        .HasColumnType("bigint");

                    b.HasKey("spa_id");

                    b.ToTable("SchoolParams");
                });

            modelBuilder.Entity("Domain.Entities.SchoolStaff", b =>
                {
                    b.Property<long>("stf_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("stf_id"));

                    b.Property<string>("stf_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("stf_banid")
                        .HasColumnType("bigint");

                    b.Property<string>("stf_cnicFileLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_cnicFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("stf_dob")
                        .HasColumnType("date");

                    b.Property<string>("stf_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("stf_isactive")
                        .HasColumnType("bit");

                    b.Property<string>("stf_joiningdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("stf_lefton")
                        .HasColumnType("date");

                    b.Property<long>("stf_monthlySalary")
                        .HasColumnType("bigint");

                    b.Property<string>("stf_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_nextOfKin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_ntnNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_pictureFileLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_pictureFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("stf_schid")
                        .HasColumnType("bigint");

                    b.Property<string>("stf_staffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stf_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("stf_teacherorStaff")
                        .HasColumnType("bit");

                    b.HasKey("stf_id");

                    b.ToTable("schoolStaff");
                });

            modelBuilder.Entity("Domain.Entities.Schools", b =>
                {
                    b.Property<long>("sch_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sch_id"));

                    b.Property<bool>("sch_active")
                        .HasColumnType("bit");

                    b.Property<string>("sch_address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("sch_city")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("sch_fbid")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("sch_governmentapproved")
                        .HasColumnType("bit");

                    b.Property<bool>("sch_governmentschool")
                        .HasColumnType("bit");

                    b.Property<string>("sch_instaid")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("sch_linkedinid")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("sch_mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sch_name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("sch_othercontactmobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("sch_othercontactname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sch_phonenumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("sch_principalname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sch_principlemobilenumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("sch_twitterid")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("sch_voiceprincipalmobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("sch_voiceprincipalname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sch_website")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("sch_id");

                    b.ToTable("schools");
                });

            modelBuilder.Entity("Domain.Entities.SectionTeachers", b =>
                {
                    b.Property<long>("ste_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ste_id"));

                    b.Property<bool>("ste_mainTeacher")
                        .HasColumnType("bit");

                    b.Property<long>("ste_schid")
                        .HasColumnType("bigint");

                    b.Property<long>("ste_sectionID")
                        .HasColumnType("bigint");

                    b.Property<long>("ste_teacherID")
                        .HasColumnType("bigint");

                    b.Property<int>("ste_year")
                        .HasColumnType("int");

                    b.HasKey("ste_id");

                    b.ToTable("SectionTeachers");
                });

            modelBuilder.Entity("Domain.Entities.StaffEducation", b =>
                {
                    b.Property<long>("sed_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sed_id"));

                    b.Property<string>("sed_degreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sed_grades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sed_instituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("sed_schid")
                        .HasColumnType("bigint");

                    b.Property<long>("sed_staffid")
                        .HasColumnType("bigint");

                    b.Property<int>("sed_yearPassing")
                        .HasColumnType("int");

                    b.HasKey("sed_id");

                    b.ToTable("staffEducations");
                });

            modelBuilder.Entity("Domain.Entities.Subjects", b =>
                {
                    b.Property<long>("sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sub_id"));

                    b.Property<bool>("sub_active")
                        .HasColumnType("bit");

                    b.Property<string>("sub_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sub_id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Entities.TeacherSubjects", b =>
                {
                    b.Property<long>("sts_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sts_id"));

                    b.Property<long>("sts_schid")
                        .HasColumnType("bigint");

                    b.Property<long>("sts_sectionID")
                        .HasColumnType("bigint");

                    b.Property<long>("sts_subjectID")
                        .HasColumnType("bigint");

                    b.Property<long>("sts_teacherID")
                        .HasColumnType("bigint");

                    b.Property<int>("sts_year")
                        .HasColumnType("int");

                    b.HasKey("sts_id");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("Domain.Entities.Application.ApplicantGuardian", b =>
                {
                    b.HasOne("Domain.Entities.Application.Applicant", "Applicant")
                        .WithMany("Guardians")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Domain.Entities.Application.ApplicantSibling", b =>
                {
                    b.HasOne("Domain.Entities.Application.Applicant", "Applicant")
                        .WithMany("Siblings")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Domain.Entities.Application.Applicant", b =>
                {
                    b.Navigation("Guardians");

                    b.Navigation("Siblings");
                });
#pragma warning restore 612, 618
        }
    }
}
